### ISSUE TITLE
Tomcat did not start correct

### ISSUE THREAD

**Issue by mseele** [redhat-developer/rsp-server-community#107]
My tomcat starts, but remains is in status `Starting` and after a minute or two, it stops.

I guess the problem is that the Web Poller could not connect to the running instance. My "Community Server Connector (stderr)" Console is full of:

```
Exception in thread "Web Poller: Web Poller: Tomcat 10.x" java.lang.NoClassDefFoundError: Could not initialize class org.apache.felix.framework.URLHandlersStreamHandlerProxy
	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:513)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1436)
	at java.base/java.net.URL.<init>(URL.java:680)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.jboss.tools.rsp.server.spi.model.polling.WebPortPoller.onePing(WebPortPoller.java:39)
	at org.jboss.tools.rsp.server.spi.model.polling.WebPortPoller.onePing(WebPortPoller.java:31)
	at org.jboss.tools.rsp.server.spi.model.polling.AbstractPoller.pollerRun(AbstractPoller.java:46)
	at org.jboss.tools.rsp.server.spi.model.polling.AbstractPoller.lambda$1(AbstractPoller.java:40)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mseele** [comment]
I've opened an new issue here: https://github.com/redhat-developer/rsp-server/issues/668
Seems like a better match than this project.
